---
  name: build-lib-sdjwt-swift
  on:
    pull_request:
      types: [opened, reopened]
    push:
  
  jobs:
    build:
      runs-on: "macos-14"
      steps:
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '16.1.0'
        - uses: actions/checkout@v4
        - run:
            fastlane tests